// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatRequest {
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub prompt: ::prost::alloc::string::String,
    /// 模型配置
    #[prost(message, optional, tag = "4")]
    pub model_config: ::core::option::Option<ModelProviderConfig>,
    /// 附件列表
    #[prost(message, repeated, tag = "5")]
    pub attachments: ::prost::alloc::vec::Vec<Attachment>,
    /// 请求ID
    #[prost(string, optional, tag = "6")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    /// 数据源附件 (JSON 字符串数组)
    #[prost(string, repeated, tag = "7")]
    pub data_source_attachments: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// === 新增字段 (v2) ===
    /// 系统提示词（可选，覆盖默认配置）
    #[prost(string, optional, tag = "8")]
    pub system_prompt: ::core::option::Option<::prost::alloc::string::String>,
    /// 用户提示词模板（可选，支持 {user_prompt} 变量替换）
    #[prost(string, optional, tag = "9")]
    pub user_prompt: ::core::option::Option<::prost::alloc::string::String>,
    /// Agent 运行时配置（可选，包含 Agent 服务器和 MCP 服务器配置）
    #[prost(message, optional, tag = "10")]
    pub agent_config: ::core::option::Option<ChatAgentConfig>,
    /// 服务类型（可选，"RCoder" 或 "ComputerAgentRunner"，默认 "RCoder"）
    #[prost(string, optional, tag = "11")]
    pub service_type: ::core::option::Option<::prost::alloc::string::String>,
    /// 用户ID（可选，ComputerAgentRunner 模式必填）
    #[prost(string, optional, tag = "12")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatResponse {
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub success: bool,
    #[prost(string, optional, tag = "4")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    /// 🆕 业务错误码（如 "9010", "VALIDATION_ERROR"）
    #[prost(string, optional, tag = "6")]
    pub error_code: ::core::option::Option<::prost::alloc::string::String>,
    /// 🆕 Resume 失败标识 (用于 rcoder 层降级处理)
    ///
    /// true 表示需要降级重试
    #[prost(bool, tag = "7")]
    pub need_fallback: bool,
    /// 降级原因：如 "session_not_found"
    #[prost(string, optional, tag = "8")]
    pub fallback_reason: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProgressRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
/// ProgressEvent 进度事件（简化版：完全透传 ACP JSON）
///
/// 设计理念：不再尝试映射 ACP 到固定的事件类型，而是直接透传 ACP 消息的 JSON
/// 优势：
///
/// 1. 零字段丢失：完整保留 ACP 结构
/// 1. 零维护成本：ACP 协议更新时后端无需修改
/// 1. 前端灵活性：前端可按需解析任意字段
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProgressEvent {
    /// 消息主类型：SessionPromptStart, SessionPromptEnd, AgentSessionUpdate, Heartbeat
    #[prost(string, tag = "1")]
    pub message_type: ::prost::alloc::string::String,
    /// 消息子类型：agent_message_chunk, tool_call, plan, end_turn 等
    #[prost(string, tag = "2")]
    pub sub_type: ::prost::alloc::string::String,
    /// ACP 消息的完整 JSON 载荷
    #[prost(string, tag = "3")]
    pub payload: ::prost::alloc::string::String,
    /// 可选的请求 ID，用于关联请求和响应
    #[prost(string, optional, tag = "4")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    /// 时间戳 (使用 Unix timestamp，单位：毫秒)
    #[prost(int64, tag = "11")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelRequest {
    /// 可选，为空时使用 project_id 查找
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    /// 用于按项目取消（当 session_id 为空时）
    #[prost(string, tag = "3")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(enumeration = "CancelResultType", tag = "2")]
    pub result: i32,
    #[prost(string, optional, tag = "3")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolvePermissionRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub option_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub cancelled: bool,
    #[prost(bool, tag = "5")]
    pub save_rule: bool,
    #[prost(string, tag = "6")]
    pub project_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "7")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolvePermissionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub outcome_json: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "5")]
    pub rule_saved: bool,
    #[prost(string, optional, tag = "6")]
    pub error_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStatusRequest {
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    /// 新增：支持通过 session_id 查询
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStatusResponse {
    /// "idle", "busy", "error"
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// Agent 是否存在于 Registry
    #[prost(bool, tag = "2")]
    pub is_found: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopAgentRequest {
    /// 项目 ID (必填)
    #[prost(string, tag = "1")]
    pub project_id: ::prost::alloc::string::String,
    /// 可选的停止原因
    #[prost(string, optional, tag = "2")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    /// 是否强制停止（不等待当前任务完成）
    #[prost(bool, tag = "3")]
    pub force: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopAgentResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 停止结果：stopped, not_found, already_stopped, error
    #[prost(string, tag = "2")]
    pub result: ::prost::alloc::string::String,
    /// 可选的详细消息
    #[prost(string, optional, tag = "3")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
    /// 被停止的 Agent 的项目 ID
    #[prost(string, tag = "4")]
    pub project_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelProviderConfig {
    /// 模型配置唯一标识（必须保留原始值，用于会话复用判断）
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 提供商名称 (如: glm, anthropic, openai, qwen)
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    /// 默认模型名称
    #[prost(string, tag = "3")]
    pub model: ::prost::alloc::string::String,
    /// API 密钥
    #[prost(string, optional, tag = "4")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
    /// API 基础 URL
    #[prost(string, optional, tag = "5")]
    pub api_base: ::core::option::Option<::prost::alloc::string::String>,
    /// 是否需要 OpenAI 兼容的认证
    #[prost(bool, optional, tag = "6")]
    pub requires_openai_auth: ::core::option::Option<bool>,
    /// 模型接口协议类型 (anthropic/openai)
    #[prost(string, optional, tag = "7")]
    pub api_protocol: ::core::option::Option<::prost::alloc::string::String>,
    /// 线路 API 格式: "chat" 表示 Chat Completions API, "response" 表示 Responses API
    #[prost(string, optional, tag = "8")]
    pub wire_api: ::core::option::Option<::prost::alloc::string::String>,
}
/// 附件数据源
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AttachmentSource {
    #[prost(oneof = "attachment_source::Source", tags = "1, 2, 3")]
    pub source: ::core::option::Option<attachment_source::Source>,
}
/// Nested message and enum types in `AttachmentSource`.
pub mod attachment_source {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Source {
        /// 文件路径
        #[prost(string, tag = "1")]
        FilePath(::prost::alloc::string::String),
        /// Base64 编码数据
        #[prost(message, tag = "2")]
        Base64(super::Base64Data),
        /// URL 链接
        #[prost(string, tag = "3")]
        Url(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Base64Data {
    #[prost(string, tag = "1")]
    pub data: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub mime_type: ::prost::alloc::string::String,
}
/// 图像尺寸
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageDimensions {
    #[prost(uint32, tag = "1")]
    pub width: u32,
    #[prost(uint32, tag = "2")]
    pub height: u32,
}
/// 文本附件
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextAttachment {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<AttachmentSource>,
    #[prost(string, optional, tag = "3")]
    pub filename: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
/// 图像附件
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageAttachment {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<AttachmentSource>,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub filename: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub dimensions: ::core::option::Option<ImageDimensions>,
}
/// 音频附件
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioAttachment {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<AttachmentSource>,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub filename: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// 时长（秒）
    #[prost(double, optional, tag = "6")]
    pub duration: ::core::option::Option<f64>,
}
/// 文档附件
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DocumentAttachment {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<AttachmentSource>,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub filename: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// 文件大小（字节）
    #[prost(uint64, optional, tag = "6")]
    pub size: ::core::option::Option<u64>,
}
/// 附件枚举（使用 oneof 区分类型）
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attachment {
    #[prost(oneof = "attachment::AttachmentType", tags = "1, 2, 3, 4")]
    pub attachment_type: ::core::option::Option<attachment::AttachmentType>,
}
/// Nested message and enum types in `Attachment`.
pub mod attachment {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum AttachmentType {
        #[prost(message, tag = "1")]
        Text(super::TextAttachment),
        #[prost(message, tag = "2")]
        Image(super::ImageAttachment),
        #[prost(message, tag = "3")]
        Audio(super::AudioAttachment),
        #[prost(message, tag = "4")]
        Document(super::DocumentAttachment),
    }
}
/// Agent 运行时配置
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatAgentConfig {
    /// 单个 Agent 服务器配置（可选）
    #[prost(message, optional, tag = "1")]
    pub agent_server: ::core::option::Option<ChatAgentServerConfig>,
    /// MCP 服务器配置（多个）
    #[prost(map = "string, message", tag = "2")]
    pub context_servers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ChatContextServerConfig,
    >,
}
/// 单个 Agent 服务器配置
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatAgentServerConfig {
    /// Agent 标识符（可选，默认 "claude-code-acp"）
    #[prost(string, optional, tag = "1")]
    pub agent_id: ::core::option::Option<::prost::alloc::string::String>,
    /// 执行命令
    #[prost(string, optional, tag = "2")]
    pub command: ::core::option::Option<::prost::alloc::string::String>,
    /// 命令参数
    #[prost(string, repeated, tag = "3")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 环境变量
    #[prost(map = "string, string", tag = "4")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 元数据
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 模型环境变量显式绑定规则
    #[prost(message, repeated, tag = "6")]
    pub model_env_bindings: ::prost::alloc::vec::Vec<ModelEnvBinding>,
    /// Permission approval mode: "yolo" (default) or "ask"
    #[prost(string, optional, tag = "7")]
    pub agent_mode: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelEnvBinding {
    /// Agent 子进程环境变量名
    #[prost(string, tag = "1")]
    pub env_key: ::prost::alloc::string::String,
    /// 绑定来源
    #[prost(enumeration = "ModelEnvBindingSource", tag = "2")]
    pub source: i32,
}
/// MCP 服务器配置
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatContextServerConfig {
    /// 服务器来源类型: "custom" 或 "local"
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// 是否启用
    #[prost(bool, tag = "2")]
    pub enabled: bool,
    /// 执行命令 (如 "bunx", "uvx", "npx")
    #[prost(string, optional, tag = "3")]
    pub command: ::core::option::Option<::prost::alloc::string::String>,
    /// 命令参数
    #[prost(string, repeated, tag = "4")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 环境变量
    #[prost(map = "string, string", tag = "5")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// 容器状态查询请求
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetContainerStatusRequest {
    /// 用户ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 项目ID
    #[prost(string, tag = "2")]
    pub project_id: ::prost::alloc::string::String,
}
/// 容器状态响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetContainerStatusResponse {
    /// 容器是否活跃（有活跃任务）
    #[prost(bool, tag = "1")]
    pub is_active: bool,
    /// 活跃任务数
    #[prost(int32, tag = "2")]
    pub active_tasks: i32,
    /// 容器运行时长（秒）
    #[prost(int64, tag = "3")]
    pub uptime_seconds: i64,
    /// 状态描述：Active, Idle, Processing
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    /// 可选：CPU 使用率（百分比，0-100）
    #[prost(double, optional, tag = "5")]
    pub cpu_percent: ::core::option::Option<f64>,
    /// 可选：内存使用（MB）
    #[prost(int64, optional, tag = "6")]
    pub memory_mb: ::core::option::Option<i64>,
}
/// VNC 状态查询请求
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVncStatusRequest {
    /// 用户ID（可选，用于日志记录）
    #[prost(string, optional, tag = "1")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    /// 项目ID（可选，用于日志记录）
    #[prost(string, optional, tag = "2")]
    pub project_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// VNC 状态响应
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVncStatusResponse {
    /// VNC 是否已就绪（x11vnc 进程 + 5900 端口）
    #[prost(bool, tag = "1")]
    pub vnc_ready: bool,
    /// noVNC 是否已就绪（6080 端口）
    #[prost(bool, tag = "2")]
    pub novnc_ready: bool,
    /// 状态描述消息
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// 容器启动时间（秒）
    #[prost(int64, tag = "4")]
    pub uptime_seconds: i64,
}
/// 取消结果类型（对应 Rust CancelResult）
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CancelResultType {
    CancelResultUnspecified = 0,
    CancelResultSuccess = 1,
    CancelResultFailed = 2,
    CancelResultTimeout = 3,
}
impl CancelResultType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CancelResultUnspecified => "CANCEL_RESULT_UNSPECIFIED",
            Self::CancelResultSuccess => "CANCEL_RESULT_SUCCESS",
            Self::CancelResultFailed => "CANCEL_RESULT_FAILED",
            Self::CancelResultTimeout => "CANCEL_RESULT_TIMEOUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CANCEL_RESULT_UNSPECIFIED" => Some(Self::CancelResultUnspecified),
            "CANCEL_RESULT_SUCCESS" => Some(Self::CancelResultSuccess),
            "CANCEL_RESULT_FAILED" => Some(Self::CancelResultFailed),
            "CANCEL_RESULT_TIMEOUT" => Some(Self::CancelResultTimeout),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModelEnvBindingSource {
    Unspecified = 0,
    ApiKey = 1,
    BaseUrl = 2,
    DefaultModel = 3,
    ProviderName = 4,
}
impl ModelEnvBindingSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MODEL_ENV_BINDING_SOURCE_UNSPECIFIED",
            Self::ApiKey => "MODEL_ENV_BINDING_SOURCE_API_KEY",
            Self::BaseUrl => "MODEL_ENV_BINDING_SOURCE_BASE_URL",
            Self::DefaultModel => "MODEL_ENV_BINDING_SOURCE_DEFAULT_MODEL",
            Self::ProviderName => "MODEL_ENV_BINDING_SOURCE_PROVIDER_NAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODEL_ENV_BINDING_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "MODEL_ENV_BINDING_SOURCE_API_KEY" => Some(Self::ApiKey),
            "MODEL_ENV_BINDING_SOURCE_BASE_URL" => Some(Self::BaseUrl),
            "MODEL_ENV_BINDING_SOURCE_DEFAULT_MODEL" => Some(Self::DefaultModel),
            "MODEL_ENV_BINDING_SOURCE_PROVIDER_NAME" => Some(Self::ProviderName),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod agent_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Agent 核心服务
    #[derive(Debug, Clone)]
    pub struct AgentServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AgentServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AgentServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AgentServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AgentServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 聊天对话接口 (Unary)
        pub async fn chat(
            &mut self,
            request: impl tonic::IntoRequest<super::ChatRequest>,
        ) -> std::result::Result<tonic::Response<super::ChatResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/agent.AgentService/Chat");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("agent.AgentService", "Chat"));
            self.inner.unary(req, path, codec).await
        }
        /// 订阅会话进度流 (Server Streaming)
        /// 替代原有的 /agent/progress/{session_id} SSE 接口
        pub async fn subscribe_progress(
            &mut self,
            request: impl tonic::IntoRequest<super::ProgressRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ProgressEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agent.AgentService/SubscribeProgress",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.AgentService", "SubscribeProgress"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// 取消会话任务 (Unary)
        pub async fn cancel_session(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agent.AgentService/CancelSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.AgentService", "CancelSession"));
            self.inner.unary(req, path, codec).await
        }
        /// Resolve a pending ACP permission request (Unary)
        pub async fn resolve_permission(
            &mut self,
            request: impl tonic::IntoRequest<super::ResolvePermissionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResolvePermissionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agent.AgentService/ResolvePermission",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.AgentService", "ResolvePermission"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取 Agent 状态 (Unary)
        pub async fn get_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agent.AgentService/GetStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.AgentService", "GetStatus"));
            self.inner.unary(req, path, codec).await
        }
        /// 停止特定 project_id 的 Agent (Unary)
        /// 用于 ComputerAgentRunner 模式：停止单个项目的 Agent，不销毁容器
        pub async fn stop_agent(
            &mut self,
            request: impl tonic::IntoRequest<super::StopAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StopAgentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agent.AgentService/StopAgent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.AgentService", "StopAgent"));
            self.inner.unary(req, path, codec).await
        }
        /// 查询容器状态 (Unary)
        /// 专门用于容器生命周期管理，返回容器活跃状态和任务信息
        pub async fn get_container_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetContainerStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetContainerStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agent.AgentService/GetContainerStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.AgentService", "GetContainerStatus"));
            self.inner.unary(req, path, codec).await
        }
        /// 查询 VNC 服务状态 (Unary)
        /// 用于检测容器内 VNC/noVNC 服务是否已启动就绪
        pub async fn get_vnc_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetVncStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetVncStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/agent.AgentService/GetVncStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.AgentService", "GetVncStatus"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod agent_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AgentServiceServer.
    #[async_trait]
    pub trait AgentService: std::marker::Send + std::marker::Sync + 'static {
        /// 聊天对话接口 (Unary)
        async fn chat(
            &self,
            request: tonic::Request<super::ChatRequest>,
        ) -> std::result::Result<tonic::Response<super::ChatResponse>, tonic::Status>;
        /// Server streaming response type for the SubscribeProgress method.
        type SubscribeProgressStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ProgressEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// 订阅会话进度流 (Server Streaming)
        /// 替代原有的 /agent/progress/{session_id} SSE 接口
        async fn subscribe_progress(
            &self,
            request: tonic::Request<super::ProgressRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SubscribeProgressStream>,
            tonic::Status,
        >;
        /// 取消会话任务 (Unary)
        async fn cancel_session(
            &self,
            request: tonic::Request<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status>;
        /// Resolve a pending ACP permission request (Unary)
        async fn resolve_permission(
            &self,
            request: tonic::Request<super::ResolvePermissionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResolvePermissionResponse>,
            tonic::Status,
        >;
        /// 获取 Agent 状态 (Unary)
        async fn get_status(
            &self,
            request: tonic::Request<super::GetStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatusResponse>,
            tonic::Status,
        >;
        /// 停止特定 project_id 的 Agent (Unary)
        /// 用于 ComputerAgentRunner 模式：停止单个项目的 Agent，不销毁容器
        async fn stop_agent(
            &self,
            request: tonic::Request<super::StopAgentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StopAgentResponse>,
            tonic::Status,
        >;
        /// 查询容器状态 (Unary)
        /// 专门用于容器生命周期管理，返回容器活跃状态和任务信息
        async fn get_container_status(
            &self,
            request: tonic::Request<super::GetContainerStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetContainerStatusResponse>,
            tonic::Status,
        >;
        /// 查询 VNC 服务状态 (Unary)
        /// 用于检测容器内 VNC/noVNC 服务是否已启动就绪
        async fn get_vnc_status(
            &self,
            request: tonic::Request<super::GetVncStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetVncStatusResponse>,
            tonic::Status,
        >;
    }
    /// Agent 核心服务
    #[derive(Debug)]
    pub struct AgentServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AgentServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AgentServiceServer<T>
    where
        T: AgentService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/agent.AgentService/Chat" => {
                    #[allow(non_camel_case_types)]
                    struct ChatSvc<T: AgentService>(pub Arc<T>);
                    impl<T: AgentService> tonic::server::UnaryService<super::ChatRequest>
                    for ChatSvc<T> {
                        type Response = super::ChatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::chat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ChatSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agent.AgentService/SubscribeProgress" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeProgressSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::ServerStreamingService<super::ProgressRequest>
                    for SubscribeProgressSvc<T> {
                        type Response = super::ProgressEvent;
                        type ResponseStream = T::SubscribeProgressStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProgressRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::subscribe_progress(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeProgressSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agent.AgentService/CancelSession" => {
                    #[allow(non_camel_case_types)]
                    struct CancelSessionSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::CancelRequest>
                    for CancelSessionSvc<T> {
                        type Response = super::CancelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::cancel_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelSessionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agent.AgentService/ResolvePermission" => {
                    #[allow(non_camel_case_types)]
                    struct ResolvePermissionSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::ResolvePermissionRequest>
                    for ResolvePermissionSvc<T> {
                        type Response = super::ResolvePermissionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ResolvePermissionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::resolve_permission(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResolvePermissionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agent.AgentService/GetStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatusSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::GetStatusRequest>
                    for GetStatusSvc<T> {
                        type Response = super::GetStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::get_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agent.AgentService/StopAgent" => {
                    #[allow(non_camel_case_types)]
                    struct StopAgentSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::StopAgentRequest>
                    for StopAgentSvc<T> {
                        type Response = super::StopAgentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StopAgentRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::stop_agent(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StopAgentSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agent.AgentService/GetContainerStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetContainerStatusSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::GetContainerStatusRequest>
                    for GetContainerStatusSvc<T> {
                        type Response = super::GetContainerStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetContainerStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::get_container_status(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetContainerStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/agent.AgentService/GetVncStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetVncStatusSvc<T: AgentService>(pub Arc<T>);
                    impl<
                        T: AgentService,
                    > tonic::server::UnaryService<super::GetVncStatusRequest>
                    for GetVncStatusSvc<T> {
                        type Response = super::GetVncStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetVncStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentService>::get_vnc_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetVncStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AgentServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "agent.AgentService";
    impl<T> tonic::server::NamedService for AgentServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
