[package]
name = "container-runtime-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
publish = false

[dependencies]
shared_types = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true }
utoipa = { workspace = true }
winnow = { workspace = true }
