apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgresql
    {{- include "rcoder.labels" . | nindent 4 }}
spec:
  selector:
    app: postgresql
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
